### PR TITLE
Update all dependency versions except protobuf

### PR DESCRIPTION
**Pull request by mbland**
Also introduces the use of maven_install.json with rules_jvm_external to track JAR dependencies instead of MODULE.bazel.lock.

We can't update protobuf to the latest version, 27.2, because grpc-java depends on version 23.1 and breaks if we upgrade it:

```
ERROR: .../external/grpc-java~/protobuf/BUILD.bazel:3:13:
  Building external/grpc-java~/protobuf/libprotobuf.jar (6 source files)
  failed: (Exit 1): java failed: error executing Javac command
  (from target @@grpc-java~//protobuf:protobuf)
  external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/java
  '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
  '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ...
  (remaining 19 arguments skipped)
external/grpc-java~/protobuf/src/main/java/io/grpc/protobuf/StatusProto.java:190:
  error: cannot access Builder
        .setCode(status.getCode().value());
        ^
  class file for com.google.protobuf.GeneratedMessageV3$Builder not found
```

Note: Specifying protobuf 27.2 to generate the above also required adding com.google.j2objc:j2objc-annotations:3.0.0 to the list of maven artifacts.

### CODE REVIEW

**Review by benjaminp — APPROVED** [review]

**Comment by mbland** [comment]
I keep retrying the `test-matrix (macos, x64, monterey, 12, d04e89854b3931f4aaced77aa3a2fcad5834b3a6, true)` job, but it keeps failing with a weird timeout on the Go SDK:

- <https://github.com/EngFlow/example/actions/runs/9860259642/job/27226730890?pr=324>
- <https://opal.cluster.engflow.com/invocations/example-oss/9cb47c52-3a77-4b51-8cd7-d59a3e80b25f#console>

```txt
Executed 0 out of 7 tests: 7 tests pass.(16:45:26)
ERROR: /private/var/tmp/_bazel_ec2-user/d38a93fb1be0997380224f7bfd079801/external/rules_go~/BUILD.bazel:42:7:
GoStdlib external/rules_go~/stdlib_/pkg failed:
(Exit 34): Remote Execution Failure:
Internal: ChCgHfMQ0UNCiqLjEC0JFA-PEgtleGFtcGxlLW9zcxolCiCTdv895MyiDrqtVwguLnh6f6-bpunJkl-v4zZwItzDyhCnAQ==:
java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
---- cut here ---8<--------8<--------8<--------8<--- cut here ----
java.io.IOException: java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
	at com.engflow.storage.s3.S3ClientV2.asSyncCall(S3ClientV2.java:262)
	at com.engflow.storage.s3.S3ClientV2.upload(S3ClientV2.java:863)
	at com.engflow.re.storage.ExpirationExternalStorage.lambda$writeBlocking$1(ExpirationExternalStorage.java:257)
```

**Comment by mbland** [comment]
@jayconrod Can you peek at the failures I'm getting, described in my previous comment and currently demonstrated in the CI job, and see if they make any sense to you? I'm not sure if it's a rules_go issue, a go 1.22.5 issue, or a macOS remote execution issue. (The last seems most likely, but I have no idea yet as to why.)

FWIW, here's the contents of `rules_go~/BUILD.bazel` where the build is choking:

```bzl
# TODO(jayconrod): add a gazelle rule so gazelle can be run automatically.
# It can't go here though, because it would break anything that depends on
# rules_go but not Gazelle, including our own go_bazel_tests.
    
stdlib(
    name = "stdlib",
    cgo_context_data = select({
        "//go/platform:internal_cgo_off": None,
        "//conditions:default": ":cgo_context_data",
    }),
    visibility = ["//visibility:public"],
)
```

**Review by jayconrod — APPROVED** [review]

**Comment by jayconrod** [comment]
> @jayconrod Can you peek at the failures I'm getting, described in my previous comment and currently demonstrated in the CI job, and see if they make any sense to you? I'm not sure if it's a rules_go issue, a go 1.22.5 issue, or a macOS remote execution issue. (The last seems most likely, but I have no idea yet as to why.)

@mbland Could you please file an internal issue and tag @restingbull to triage?

This is an internal error. It looks like a macOS worker in Opal is failing to upload output files with expiration external storage. 

I don't think this is a problem with rules_go, Go, or Bazel. The `GoStdLib` action produces a few hundred output files (compiled objects) ranging from 10s to 1000s of kilobytes. From the error message, I'd guess we're tripping over some concurrency limit in the AWS SDK. Not sure why that would affect macOS in particular.

I think it's fine to merge this PR with that job failing, but if you want it to be green, you could leave rules_go and Go at their current versions.

**Comment by mbland** [comment]
> @mbland Could you please file an internal issue and tag @restingbull to triage?
> 
> This is an internal error. It looks like a macOS worker in Opal is failing to upload output files with expiration external storage.
> 
> I don't think this is a problem with rules_go, Go, or Bazel. The `GoStdLib` action produces a few hundred output files (compiled objects) ranging from 10s to 1000s of kilobytes. From the error message, I'd guess we're tripping over some concurrency limit in the AWS SDK. Not sure why that would affect macOS in particular.
> 
> I think it's fine to merge this PR with that job failing, but if you want it to be green, you could leave rules_go and Go at their current versions.

@jayconrod Thanks; it looks like @restingbull already beat me to it. I can wait a while before merging this. If we fix it on our end, I can re-run the jobs here to confirm all is indeed well.

**Review by TheGrizzlyDev — APPROVED** [review]

**Pull request merged**
